### ISSUE TITLE
Can't build today

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#29]
Hello Elie,

I tried building today (Oct 14), after the change to the clang libs instead of the binary, but I get this error when trying to link ldc2 (everything else builds fine up until linking):

deps/clang/lib/libclangFrontend.a(SerializedDiagnosticReader.cpp.o): In function `operator*':
/usr/local/include/llvm/Support/ManagedStatic.h:69: undefined reference to`AnnotateHappensAfter'
deps/clang/lib/libclangLex.a(Lexer.cpp.o): In function `llvm::sys::UnicodeCharSet::rangesAreValid() const':
/usr/local/include/llvm/Support/UnicodeCharRanges.h:71: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:71: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:72: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:72: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:73: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:73: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:74: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:74: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:78: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:78: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:79: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:79: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:80: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:80: undefined reference to `llvm::isCurrentDebugType(char const*)'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:81: undefined reference to`llvm::DebugFlag'
/usr/local/include/llvm/Support/UnicodeCharRanges.h:81: undefined reference to `llvm::isCurrentDebugType(char const*)'
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)

I updated clang/llvm to the latest 3.6 version. I can see that AnnotateHappensAfter is defined in libclang_rt.tsan-x86_64.a and I try to link this lib in manually, but I still get the same errors?? Not sure what the problem is. Any ideas?

Thanks,
Kelly

**Comment by Syniurge** [comment]
Hi Kelly,

Looking into it, I noticed recently that cmake still looks inside my llvm build folder for some files. Not what I was aiming for..

**Comment by Syniurge** [comment]
It happens when building debug Clang libs against a release LLVM. Seems like the only way to build Calypso against Ubuntu's LLVM packages is to build it in release mode, and to get it to build in debug mode you need to build and install LLVM yourself first.

I need to add a check that `llvm-config --build-mode` matches the Calypso build mode.

**Comment by Syniurge** [comment]
Added by the latest commit, thanks Kelly.

Apart from that issue Calypso seems to work well with Ubuntu's LLVM 3.6 packages.
