### ISSUE TITLE
cpp11-push has undefined references

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [Syniurge/Calypso#45]
Building branch cpp11-push I get these undefined references:

`[ 18%] Linking CXX executable bin/ldc2
lib/libldc.a(cppmodule.cpp.o): I funktionen "cpp::DeclMapper::VisitTemplateParameter(clang::NamedDecl const*, clang::TemplateArgument const*)":`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/dmd2/cpp/cppmodule.cpp:1040: undefined reference to `Array<RootObject*>* cpp::TypeMapper::FromType::fromTemplateArgument<false>(clang::TemplateArgument const*, clang::NamedDecl const*)'`

`lib/libldc.a(cppexpression.cpp.o): I funktionen "cpp::fromASTTemplateArgumentListInfo(Loc, clang::TemplateArgumentLoc const*, unsigned int, cpp::TypeMapper&)":`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/dmd2/cpp/cppexpression.cpp:64: undefined reference to `Array<RootObject*>* cpp::TypeMapper::FromType::fromTemplateArgument<false>(clang::TemplateArgument const*, clang::NamedDecl const*)'`

`lib/libldc.a(cpptemplate.cpp.o): I funktionen "cpp::TemplateInstance::semanticTiargs(Scope*)":`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/dmd2/cpp/cpptemplate.cpp:790: undefined reference to `Array<RootObject*>* cpp::TypeMapper::FromType::fromTemplateArgument<false>(clang::TemplateArgument const*, clang::NamedDecl const*)'`

**Comment by Syniurge** [comment]
Hi and thanks for the report!

Which compiler are you using? Does 9249edcf3a2c8904cc50911643d764cd1afadf3f fix the linking errors?

**Comment by ThomasBrixLarsen** [comment]
GCC 6.1.1 on Arch. The commit did indeed help.

Though now I get an error later while building phobos.

`[ 74%] Generating std/variant-debug.o
/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7189): Error: this for dbgVerifySorted needs to be type SortedRange not type SortedRange!(uint[], pred)`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7241): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7248): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7254): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7262): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7268): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7276): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7285): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7305): Error: need 'this' for '_input' of type 'uint[]'`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/range/package.d(7798): Error: template instance std.range.SortedRange!(uint[], pred) error instantiating`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/uni.d(2962):        instantiated from here: assumeSorted!("a<=b", uint[])`

`/home/tbl/PKGBUILD/ldc-calypso-git/src/ldc/runtime/phobos/std/uni.d(1855):        instantiated from here: InversionList!(GcPolicy)`

`make[2]: *** [runtime/CMakeFiles/phobos2-ldc-debug.dir/build.make:610: runtime/std/uni-debug.o] Error 1`

The samme error happens when generating std/uuid.o.

**Comment by Syniurge** [comment]
It should be fixed by 0636bfbe165a46f7544ed7e45a480520853b71b7.

I really need to stop pushing half-tested commits..

**Comment by ThomasBrixLarsen** [comment]
It compiles now.

It still doesn't work with Qt 5.7, but good to see progress.

**Comment by Syniurge** [comment]
Currently most of the libstdc++ examples compile with `-cpp-args -std=c++11`, and I'm working on Qt 5.7 support which should be not too far away (needed: C++11 constexpr functions calls in D's CTFE for `QBasicAtomicInteger` and `std::atomic<int>` constants, which seems doable and I hope to get it working this week-end).

**Comment by ThomasBrixLarsen** [comment]
That's great. Qt 5.7 and Android support would make me able to start looking into using D in our products at work.
